export const PATH = {
  objectCardPage: '/object-card-page',
  newsCardPage: '/news-card-page',
  routeCardPage: '/route-card-page',
  notificationsPage: '/notifications-page',
  createObjectCardPage: '/create-object-card-page',
  createNewsCardPage: '/create-news-card-page',
  createRouteCardPage: '/create-route-card-page',
  createUsersPage: '/create-users-page',
  createNotificationsPage: '/create-notifications-page',
  editNewsCardPage: '/edit-news-card-page',
  usersPage: '/users-page',
  settingsPage: '/settings-page',
  auth: '/auth',
  error404: '/error404',
}
